apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-gscj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-gscj
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-gscj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-gscj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-gscj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-afjb-tenant/status-quarkus-io/statusquarkusio-gscj@sha256:5ed3170794813df2cf5b44d1fb46e7f624f23dbfa1c5210cc2056984e8ca3663
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
